# -*- coding: utf-8 -*-
"""torresHanoiRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class TorresHanoi:
    """
    Clase que resuelve recursivamente el problema de las Torres de Hanoi.
    """

    def __init__(self, num_discos):
        """
        Inicializa el número de discos.
        :param num_discos: int - Número de discos a mover.
        """
        self.num_discos = num_discos

    def mover(self, n=None, origen='A', destino='C', auxiliar='B'):
        """
        Método recursivo que imprime los pasos para mover los discos.
        :param n: int - Número de discos a mover (opcional).
        :param origen: str - Torre de origen.
        :param destino: str - Torre de destino.
        :param auxiliar: str - Torre auxiliar.
        """
        if n is None:
            n = self.num_discos

        # Caso base
        if n == 1:
            print(f"Mover disco de {origen} a {destino}")
        else:
            # Mover n-1 discos al auxiliar
            self.mover(n-1, origen, auxiliar, destino)
            # Mover disco mayor al destino
            self.mover(1, origen, destino, auxiliar)
            # Mover n-1 discos del auxiliar al destino
            self.mover(n-1, auxiliar, destino, origen)

    def mostrar_solucion(self):
        """
        Muestra todos los pasos de la solución.
        """
        print(f"\nSolución para {self.num_discos} discos en Torres de Hanoi:\n")
        self.mover()
        print("\n==============================\n")


# ============================================
# EJECUCIÓN DEL PROGRAMA
# ============================================
if __name__ == "__main__":
    print("=== Torres de Hanoi Recursiva ===")
    try:
        num_discos = int(input("Ingrese el número de discos: "))
        if num_discos < 1:
            print(" Error: debe ingresar al menos 1 disco.")
        else:
            hanoi = TorresHanoi(num_discos)
            hanoi.mostrar_solucion()
    except ValueError:
        print(" Error: debe ingresar un número entero válido.")